### PR TITLE
Timer 🍎

### PR DESCRIPTION
**Pull request by Overpoweredplatypus**
This push request includes:

- First draft of README.md
- The bot can now create a timer upon request and inform that it's been created.
- Added an empty test class

### CODE REVIEW

**Review by sailoraria — CHANGES_REQUESTED** [review]
Typo: "Users can create events for exams..." in line 10 of the readme

**Review by xinyue296 — COMMENTED** [review]
Despite the typo mentioned by Aria, looks good to me!

**Review by christianjokhaji — CHANGES_REQUESTED** [review]
Code looks good! I would just update the comments and Javadoc in TimerInteractor.java (refers to starting a game) and remove the duplicated !ping functionality since it already exists in EventListener.java.

**Review by christianjokhaji — APPROVED** [review]

**Review by xinyue296 — APPROVED** [review]
Looks good to me! Can't wait to try the new timer feature!

**Review by sailoraria — APPROVED** [review]
great thanks for editing it!

**Pull request merged**
